# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170719_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='click_count',
        ),
    ]
