# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_user_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
    ]
